"""is_woman was added

Revision ID: 9d1c4ec25d10
Revises: f130fb354ca4
Create Date: 2024-08-01 19:23:03.683450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1c4ec25d10'
down_revision: Union[str, None] = 'f130fb354ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('is_woman', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero', 'is_woman')
    # ### end Alembic commands ###
